/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/polak.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/polak.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <group name="thePolak2">
            <skinnedMesh name="thePolak2_1" geometry={nodes.thePolak2_1.geometry} material={materials['ThePolac2-Material.001']} skeleton={nodes.thePolak2_1.skeleton} />
            <skinnedMesh name="thePolak2_2" geometry={nodes.thePolak2_2.geometry} material={materials['palette.004']} skeleton={nodes.thePolak2_2.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/polak.glb')
